download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",  "Electric power consumption.zip")
dataFile <- unzip("Electric power consumption.zip")
dataTable <- read.table(dataFile, sep = ";", header = T)
dataExtra <- dataTable[dataTable$Date == "1/2/2007" | dataTable$Date == "2/2/2007",]
Date_Time <- paste(dataExtra$Date, dataExtra$Time)
dataExtra["Date_Time"] <- Date_Time
dataExtra$Date_Time <- strptime(dataExtra$Date_Time, format = "%d/%m/%Y %H:%M:%S")
dataExtra$Global_active_power <- as.character(dataExtra$Global_active_power)
dataExtra$Global_active_power <- as.numeric(dataExtra$Global_active_power)
dataExtra$Sub_metering_1 <- as.numeric(as.character(dataExtra$Sub_metering_1))
dataExtra$Sub_metering_2 <- as.numeric(as.character(dataExtra$Sub_metering_2))
dataExtra$Sub_metering_3 <- as.numeric(as.character(dataExtra$Sub_metering_3))
dataExtra$Voltage <- as.numeric(as.character(dataExtra$Voltage))
dataExtra$Global_reactive_power <- as.numeric(as.character(dataExtra$Global_reactive_power))
par(mfrow = c(2,2), mar = c(4,4,2,1))
with(dataExtra, plot(Date_Time, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)"))
with(dataExtra, plot(Date_Time, Voltage, type = "l", xlab = "deadtime", ylab = "voltage"))
with(dataExtra, plot(Date_Time, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(dataExtra, lines(Date_Time, Sub_metering_2, type = "l", col = "red"))
with(dataExtra, lines(Date_Time, Sub_metering_3, type = "l", col = "blue"))
legend("topright", bty = "n", cex = 0.5, y.intersp = 0.2,col = c("black", "red", "blue"), lty = 7, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(dataExtra, plot(Date_Time, Global_reactive_power, type = "l", xlab = "deadtime", ylab = "Global_reactive_power"))